# Generated by Django 5.0.10 on 2025-01-03 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'rol': 'Cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='viajes_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='conductor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'Conductor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viajes_conductor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
    ]
